spring:
  mail:
    username: ajunsu5@gmail.com
    password: knjsqpcpktqcktpo
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 76055062033-r8muoeqqn6pfbc5p0ioeke5b6pprri5q.apps.googleusercontent.com
            client-secret: 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
          naver:
            client-id: oWEOo_raUlZ4_VJVMVeI
            client-secret: BV8LJzFwSH
          kakao:
            clientId: 03b0b14d4fbf423e03b10178a227d48c
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  kakao:
    rest:
      api:
        key: 03b0b14d4fbf423e03b10178a227d48c
